# Generated by Django 5.1.1 on 2024-10-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalsystem', '0003_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
