# Generated by Django 5.1.1 on 2024-10-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalsystem', '0005_patient_is_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_emergency',
        ),
    ]
