# Generated by Django 5.1.1 on 2024-10-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalsystem', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
